public class OperadoresAritmeticos {
    public static void main(String[] args) {
        double numero1 = 7.0;
        double numero2 = 5.0;

        System.out.println("Operaciones con \"numero1\" (" + numero1 + ") y \"numero2\" (" + numero2 + "):");

        System.out.println("Suma: " + (numero1 + numero2));
        System.out.println("Resta: " + (numero1 - numero2));
        System.out.println("Multiplicación: " + (numero1 * numero2));
        System.out.println("División: " + (numero1 / numero2));
        System.out.println("Módulo / Resto: " + (numero1 % numero2));